const DEFAULT_PROGRAM = [
  ["say",{"text":"Welcome!"}], 
  ["wait",{}], 
  ["openYTPlayer",{"videoId":"6ZR-P_nfMj4"}], 
  ["say",{"text":"Today we're going to watch a video of the best university.","pitch":"0.7"}], 
  ["playYTVideo",{}], 
  ["waitYTVideoTime",{"time":"12"}], 
  ["volumneYTPlayer",{"volumne":"25"}], 
  ["say",{"text":"Oh that's nice. You have to see this further! Wow!"}], 
  ["volumneYTPlayer",{"volumne":"100"}], 
  ["waitYTVideoTime",{"time":"28.5"}], 
  ["pauseYTVideo",{}], 
  ["say",{"text":"Wow! I have to see it again!"}], 
  ["seekYTVideo",{"time":"27"}], 
  ["playYTVideo",{}], 
  ["waitYTVideoTime",{"time":"45"}], 
  ["changeYTVideo",{"videoId":"AxMMKQliIz8"}], 
  ["say",{"text":"Let’s watch another video. The internet is made up of 70% cats and 45% scam."}], 
  ["waitYTVideoTime",{"time":"20"}], 
  ["changeYTVideo",{"videoId":"q5FwsIkJCXU"}], 
  ["seekYTVideo",{"time":"1:28"}], 
  ["volumneYTPlayer",{"volumne":"50"}], 
  ["say",{"text":"Critical Computer Alert from Microsoft! Your computer has Eight hundred forty one point three viruses. Please do not switch off, otherwise the computer will be locked forever. Transfer four hundred one point ninety-nine euro to fjang's banking account, and your problem will be solved by professionally trained experts.","pitch":1.15,"rate":1.3,"voice":"Bangla India Male"}], 
  ["volumneYTPlayer",{"volumne":"100"}], 
  ["alert",{"text":"Critical Computer Alert from Microsoft!"}], 
  ["pauseYTVideo",{}], 
  ["say",{"text":"ciao!","pitch":"0.6","rate":"0.5"}]
];
